using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PizzaApp.Refactored._09.Domain
{
    public class BaseEntity
    {   
        [Key] // Primary Key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Autogenerated by the database
        public int Id { get; set; }
    }
}
